### ISSUE TITLE
User should be able to exclude files

### ISSUE THREAD

**Issue by benjaminrosenbaum** [DCgov/poirot#28]
I want to exclude things like minimized .js files and css files, otherwise the output is overwhelming.

**Comment by emanuelfeld** [comment]
Not going to implement this. Output is only every overwhelming if you're doing a --revlist="all" on an existing repo with a lot of revisions. That should only happen once (if ever). I think it's correct that the way to ignore files is to add them to the .gitignore. Otherwise they should be checked.
