### ISSUE TITLE
Don't overwrite the pre-commit hook

### ISSUE THREAD

**Issue by stvnrlly** [DCgov/poirot#31]
Each repo can only have one of each hook, so a better approach might be to install the script separately and have `pre-commit` call it, as recommended in http://stackoverflow.com/questions/26624368/handle-multiple-pre-commit-hooks.

For example: 

```
curl https://raw.githubusercontent.com/DCgov/poirot/master/pre-commit-poirot -o .git/hooks/pre-commit-poirot
echo "./pre-commit-poirot" >> .git/hooks/pre-commit
chmod +x .git/hooks/pre-commit-poirot
```

**Comment by emanuelfeld** [comment]
Sounds good. I was thinking most DC gov agency staff would be unlikely to have more than this as a pre-commit hook (git is a new thing for most), but this doesn't impose any additional burden. I'll re-check and modify in the morning. Thanks!

**Comment by stvnrlly** [comment]
As a bonus, I think that this would allow running Poirot through the hook with command line options, which would make something like #32 simpler.
