### ISSUE TITLE
Allow pre-commit hook to use URL for pattern file

### ISSUE THREAD

**Issue by stvnrlly** [DCgov/poirot#32]
It would be nice to be able to bundle up patterns into a single file and then share them across an organization. I'm imagining just setting a single URL, but I suppose people might want multiple.

**Comment by emanuelfeld** [comment]
You should be able to do that now. Just set patterns="your_url_here,your_other_url_here" in the commit hook.

**Comment by stvnrlly** [comment]
Nice, I didn't realize that a comma-separated list worked, though I see now that that's in the documentation. However, it doesn't look like you can use the `--patterns` flag for it, which is what I'm really looking for here.

The reason is that I'd like a script to automatically set the pattern URL when creating the hook. I can do this with `sed` if necessary, but would prefer an "official" way.

**Comment by emanuelfeld** [comment]
You totally can use the --patterns flag for URLs (maybe I'm misunderstanding), though looking over the script there needs to be notification when the URL given doesn't work…

Are you saying you'd rather not open and edit the pre-commit-poirot file to set the patterns URL(s)?

**Comment by emanuelfeld** [comment]
i.e. you want to add it as a flag when you invoke the pre-commit hook script?

**Comment by stvnrlly** [comment]
Yep, opening and editing is the manual step that I'm hoping to avoid here. I can submit a PR for it, if you'd like.

**Comment by emanuelfeld** [comment]
I'm fixing it now to use getopts!

**Comment by emanuelfeld** [comment]
There's no shell type independent version of getopts, is there?
