### ISSUE TITLE
Name of pattern in warning message

### ISSUE THREAD

**Issue by benjaminrosenbaum** [DCgov/poirot#34]
As a poirot user, when a warning message pops up on a precommit hook, the only context I have is the regex itself:

```
Running Poirot...
Pattern files:
/Users/Ben/Developer/github/poirot-patterns/default.txt
Investigating staged revisions
Investigating local revisions
Poirot reporting back: 

Pattern: @[A-Z0-9-]+\.[A-Z0-9-.]+

  File: app/__init__.py

    Line 27
     @app.errorhandler(404)

    Line 31
     @app.template_filter()

Some pattern matches were found in your staged changes. Are you sure want to commit? Choose an option #.
1) Commit
2) Cancel
```

I'm being asked here "is it okay that your code has strings that match @[A-Z0-9-]+.[A-Z0-9-.]+ ?" The problem is that I don't know what "@[A-Z0-9-]+.[A-Z0-9-.]+" is. What am I to be worried about here? If the warning said "typical email suffix"  or something, I could be like "oh, no, that's not what it is".

So it would be helpful to include a description line with each pattern and display it here.

**Comment by emanuelfeld** [comment]
Could make it a YAML/JSON file, with like:

```
- name: email address
  pattern: @[A-Z0-9-]+\.[A-Z0-9-.]+
```

Only issue is that some people are already pointing to the poirot-patterns files, so would need to update their poirot version if we make the change.
